### ISSUE TITLE
Multiple pipelines from single CodeCommit repo

### ISSUE THREAD

**Issue by eliran-allcloud** [awslabs/aws-deployment-framework#103]
currently, it is not possible to create multiple pipelines from the same CodeCommit repo.
due to CodePipeline limitation(8 targets/50 account per target), and the way the ADF works with multiple regions, we reached the maximum number of accounts per pipeline.

deployment_map.yaml should accept a new parameter to override the pipeline/repo name
```
pipelines:
  - name: mystack-eu-west-1
    type: cc-cloudformation
    region: eu-west-1
    params:
      - SourceAccountId: 111111222222
      **- RepoName: my-stack**
      - NotificationEndpoint: support@example.com
    targets:
      - path: /ou1
      - path: /ou2
      - path: /ou3
      - path: /ou4
      - path: /ou5
      - path: /ou6
      - path: /ou7
      - path: /ou8

  - name: mystack-us-east-1
    type: cc-cloudformation
    region: us-east-1
    params:
      - SourceAccountId: 111111222222
      **- RepoName: my-stack**
      - NotificationEndpoint: support@example.com
    targets:
      - path: /ou1
      - path: /ou2
      - path: /ou3
      - path: /ou4
      - path: /ou5
      - path: /ou6
      - path: /ou7
      - path: /ou8
```
