### ISSUE TITLE
CodeBuild error COMMAND_EXECUTION_ERROR

### ISSUE THREAD

**Issue by Vad1mo** [awslabs/aws-deployment-framework#110]
Not sure if this is fixed in 1.2.2, but I get this error in CodeBuild codepipeline/aws-deployment-framework-bootstrap-pipeline on the master acccount 

```

[Container] 2019/07/29 09:49:26 Phase complete: PRE_BUILD State: SUCCEEDED 
[Container] 2019/07/29 09:49:26 Phase context status code:  Message:  
[Container] 2019/07/29 09:49:26 Entering phase BUILD 
[Container] 2019/07/29 09:49:26 Running command sam build -t deployment/global.yml 
/usr/local/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version! 
  RequestsDependencyWarning) 
Error: Template file not found at /codebuild/output/src794385070/src/deployment/global.yml 
 
[Container] 2019/07/29 09:49:26 Command did not exit successfully sam build -t deployment/global.yml exit status 1 
[Container] 2019/07/29 09:49:26 Phase complete: BUILD State: FAILED 
[Container] 2019/07/29 09:49:26 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: sam build -t deployment/global.yml. Reason: exit status 1 
[Container] 2019/07/29 09:49:26 Entering phase POST_BUILD 
[Container] 2019/07/29 09:49:26 Phase complete: POST_BUILD State: SUCCEEDED 
[Container] 2019/07/29 09:49:26 Phase context status code:  Message:  
```

Going to give a try after cleanup with 1.2.2

**Comment by Vad1mo** [comment]
So, was able to update to 1.2.2, deleted everything previous, but I still see this error.

**Comment by bundyfx** [comment]
Hi @Vad1mo 

So the error states - **deployment/global.yml is not found**. Does this file exist in your bootstrap repo?

This is the default global.yml that gets commit into the bootstrap repo automatically when you install ADF.

**Comment by Vad1mo** [comment]
Nope, the file isn't there. Can I share the link to the dump to the zipped repo here?

**Comment by bundyfx** [comment]
Looking into this now. thanks.

**Comment by Vad1mo** [comment]
This is are the setting I used for SAR

```yml

Application name: aws-deployment-framework
CommitInitialBootstrapContent: true
CrossAccountAccessRoleName: OrganizationAccountAccessRole
DeploymentAccountMainRegion: us-east-1
LogLevel: DEBUG
TerminationProtection: false

DeploymentAccount: ""
DeploymentAccountEmailAddress""
DeploymentAccountId: 5-redacted-6
DeploymentAccountName: ""

DeploymentAccountTargetRegions: eu-west-1
MainNotificationEndpoint: vb@redacted.com
```
