### ISSUE TITLE
Support for .yaml extension

### ISSUE THREAD

**Issue by ikben** [awslabs/aws-deployment-framework#113]
The [YAML faq](https://yaml.org/faq.html) recommends using `.yaml` instead of `.yml` and when using `sam init` the sam cli creates a `template.yaml`, so it would be nice if ADF could treat `yml` and `yaml` the same.

This might need some edge case handling (eg. when there is both a `deployment_map.yaml` and a `deployment_map.yml`)

**Comment by bundyfx** [comment]
Hi @ikben,

Thanks for this one, I have always wanted to support this however it is a little tricky when it comes to the CodePipeline Deploy Action _TemplatePath_ Property. TemplatePath essentially wants to know the path of the file it should execute ahead of time _(when the pipeline is created)_. This means one of the only ways I think think of solving this currently, is to allow a parameter override when creating pipelines _(a property from a deployment_map)_ that allows users to define the name of the file that will go into that TemplatePath Parameter _(and have it default to template.yml)_.

Interested in your thoughts of course.
Cheers
Flynn

**Comment by bundyfx** [comment]
> Hey Flynn,
> 
> I was planning on opening an issue about supporting a configuration option for the template path, so that sounds like a fine solution.
> 
> The reason I haven't yet is that my main use case for that would have been deploying multiple templates from the same repo, possibly in the same pipeline and I was still thinking about how I would like that to work both in terms of stages and steps as in how the config might look.
> 
> Kind regards,
> Ben

Hi Ben,
As of 2.0 you can pass **template_filename** as a property of the cloudformation action which allows users to choose which template gets executed. Im interested in hearing your thoughts around how to support multiple templates. Currently the only way to do that would be using nested stacks. potentially we could make template_filename take an array of files.. then create an action per file?

Cheers!
Flynn

**Comment by ikben** [comment]
I haven't had time to test it, but I took a quick look at the user guide. Here is my current thinking.

- Multiple templates do not make a lot of sense if they are not related. I don't see a lot of value in having one pipeline that deploys multiple apps/workloads/..., even if you work with a mono-repo approach (which is our current plan)

- However within one application you might have multiple stacks. Let's assume we've split our template in 2 layers, a data-layer for everything that contains or is state and an application layer for everything else.

With the current capabilities, it seems like nested stacks are the easiest way to do this, but I dislike them for the 2 layer use case (as they will update the data-layer everytime and that is exactly what I'm trying to avoid)

If this would work like I think it does, it might be a better way:
```yaml
pipelines:
  - name: my-app
    default_providers:
      source:
        provider: codecommit
        repository: my-app
        account_id: '222222222222'
      deploy:
        provider: cloudformation
    targets:
      - target: &prod_ou /my_ou/prod
        name: data-layer-prod
        properties:
          stack_name: my-app-data-layer
          template_filename: data-layer-template.yaml
          change_set_approval: true
      - target: *prod_ou
        name: application-layer-prod
        properties:
          stack_name: my-app-application-layer
          template_filename: application-layer-template.yaml
```
This would require me to use import/export or parameter store (in the account) to pass things between those two stacks, but that would be fine.

If I think a bit about what I would like it to look like, It might be nice to collapse the targets:
```yaml
    targets:
      - target: /my_ou/prod
        steps:  # this could get a better name like stages, sub_targets or templates
          - name: data-layer
            properties:
              stack_name: my-app-data-layer # this can now be autogenerated based on the step name
              template_filename: data-layer-template.yaml # this can now be autogenerated based on the step name
              change_set_approval: true
          - name: application-layer  # example of using the auto-generated names
```

when you don't have any properties, it can be even shorter:
```yaml
    targets:
      - target: /my_ou/prod
        steps:
          - data-layer
          - application-layer
```
(or with an approve in between)

```yaml
    targets:
      - target: /my_ou/prod
        steps:
          - data-layer
          - approval
          - application-layer
```

to prevent confusion with deploying the "approval" template, maybe the steps should specify the template instead (when no name property is given)
```yaml
    targets:
      - target: /my_ou/prod
        steps:
          - data-layer.yaml
          - approval
          - application-layer.yaml
```

in that case "templates" might be a better way and I think that was what you were proposing?


None of the solutions (nested stacks, repeat targets or sub-targets) solve cross-account or cross-region deployments, but I think the `import` resolver could solve that, if the account id is not required there. Not related to this issue, but have you considered creating a "fake" stack in the account where the export is defined to "lock" the exports like they would be in a single region/account scenario)

A more intuitive solution would be allowing to set cloudformation parameters via overrides. Something like this (I might be misunderstanding parameter_overrides and I did invent the cloudformation_parameters key):

```yaml
    targets:
      - target: /my_ou/prod
        steps:
          - name: data-layer
            properties:
              outputs: data-layer-outputs
          - name: application-layer
            properties:
              param_overrides:
                - inputs: data-layer-outputs
                  param: cloudformation_parameters.RdsEndpoint  # This is also inventing a way to specify nesting
                  key_name: RdsEndpoint
```


(I do consider the original issues solved, so maybe we should re-open a new issue for the multiple-templates use case?)

Thanks,
Ben
