### ISSUE TITLE
Support approvals between generating and executing a CloudFormation ChangeSet

### ISSUE THREAD

**Issue by ikben** [awslabs/aws-deployment-framework#125]
Currently the cc-cloudformation pipeline generates both these steps sequentially

It would be nice if there was a pipeline type that:

- first creates the ChangeSets in every account/region
- Has a gate that allows for manual inspection of the changeset
- than executes those changes.

Example configuration
```
pipelines:
  - name: sample-pipeline 
    type: cc-cloudformation
    params:
      - SourceAccountId: 111111111111
      - NotificationEndpoint: your@email.com
    targets:
      - /business_unit/development # runs exactly like it does now
      - approval # does exactly what it does now
      - name /business_unit/staging
        change_set: approval_needed  # splits into two stages     
```

I know of companies going a step further and using a script to check the change set and auto-approve "safe" changes, but I think that's hard to do in CodePipeline.
