### ISSUE TITLE
2.x invoking lambda function local CodeUri

### ISSUE THREAD

**Issue by pozeus** [awslabs/aws-deployment-framework#164]
Since upgrade to 2.x version invoking a pipeline that triggers an lambda function seems broken.

The Cloudformation stack is giving below error in target account:
Status reason
Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [ProviderCreator] is invalid. 'CodeUri' is not a valid S3 Uri of the form "s3://bucket/key" with optional versionId query parameter.

Resource it is referring:
```
  IdentityProvider:
    Type: Custom::IdentityProvider
    Properties:
      ServiceToken: !GetAtt ProviderCreator.Arn
      Metadata: !Ref MetadataFile
      Name: !Ref SamlProviderName
      AccountId: !Ref AWS::AccountId

  ProviderCreator:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: './src/lambda'
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python2.7
      Timeout: 30
```

Is this caused by faulty deployment_map? section affected looks like below:
deployment_map.yml
```
  - name: iam  # The name of your pipeline (This will match the name of your repository)
    default_providers:
      source:
        provider: codecommit
        properties:
          account_id: %ACCOUNTID%  # The source account that will hold the codebase
    params:
        restart_execution_on_update: True
        notification_endpoint: %EMAIL% # The Notification (user/team/slack) responsible for this pipeline
    targets:  # Deployment stages
      - /OU1
      - /OU2
      - [/OU3, /OU4, /OU5, /deployment]
```

The lambda function is located in the repo itself as the CodeUri indicates which has been working before. Do I need to restructure how this is stored or is the deployment_map the issue?
