### ISSUE TITLE
Pipeline creation fails when using target with codebuild provider in multiple regions

### ISSUE THREAD

**Issue by at7925** [awslabs/aws-deployment-framework#168]
Pipeline creation fails with  error ”There is already a Construct with name ‘SOME-NAME-stage-1' in Stack” when using target with codebuild provider in multiple regions. Likely region should be  added to build project name.

Example:
```
pipelines:
  - name: verify-customdeploy
    default_providers:
      source:
        provider: codecommit
        properties:
          account_id: 12345000009
    targets:
      - path: /deployment
        regions: [ us-east-1, us-west-2 ]
        provider: codebuild
        properties:
          spec_filename: deployspec.yml
```
error in log:
```
2019-10-23 19:48:07,636 | INFO | cdk_stacks.main | Pipeline creation/update of verify-customdeploy commenced | (main.py:31)
jsii.errors.JavaScriptError:
Error: There is already a Construct with name 'Deploymentaccount-stage-1' in Stack [verify-customdeploy]

at ConstructNode.addChild (/tmp/jsii-kernel-Q2Pve6/node_modules/@aws-cdk/core/lib/construct.js:395:19)
at new ConstructNode (/tmp/jsii-kernel-Q2Pve6/node_modules/@aws-cdk/core/lib/construct.js:32:24)
at new Construct (/tmp/jsii-kernel-Q2Pve6/node_modules/@aws-cdk/core/lib/construct.js:435:21)
at obj._wrapSandboxCode (/codebuild/output/src518406672/src/adf-build/jsii/_embedded/jsii/jsii-runtime.js:6992:49)
at Kernel._wrapSandboxCode (/codebuild/output/src518406672/src/adf-build/jsii/_embedded/jsii/jsii-runtime.js:7447:19)
at Kernel._create (/codebuild/output/src518406672/src/adf-build/jsii/_embedded/jsii/jsii-runtime.js:6992:26)
at Kernel.create (/codebuild/output/src518406672/src/adf-build/jsii/_embedded/jsii/jsii-runtime.js:6746:21)
at KernelHost.processRequest (/codebuild/output/src518406672/src/adf-build/jsii/_embedded/jsii/jsii-runtime.js:6521:28)
at KernelHost.run (/codebuild/output/src518406672/src/adf-build/jsii/_embedded/jsii/jsii-runtime.js:6464:14)
at Immediate.setImmediate [as _onImmediate] (/codebuild/output/src518406672/src/adf-build/jsii/_embedded/jsii/jsii-runtime.js:6467:37)
at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)
at processImmediate (timers.js:658:5)
```
