### ISSUE TITLE
Permission issue using tags in targets

### ISSUE THREAD

**Issue by ErikMeinders** [awslabs/aws-deployment-framework#173]
When using the feature to use tags to identify accounts, I get the following error:

botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the GetResources operation: User: arn:aws:sts::<masteraccount>:assumed-role/OrganizationAccountAccessRole-readonly/pipeline is not authorized to perform: tag:GetResources 

when setting up deployment_map.yaml with:

```
targets: 
      - tags: 
          controlledAccount: true 
        name: controlledAccounts 

```
