### ISSUE TITLE
Upgrades should not overwrite changes to custom deployment role policies

### ISSUE THREAD

**Issue by thomasmcgannon** [awslabs/aws-deployment-framework#177]
## Problem

Currently during the bootstrap process roles and policies for deployment are created based on the global.yml files. e.g. the aws-cloudformation-deployment-role.

These files are generally customized after installing ADF to cater for specific needs however during an upgrade these customizations can be accidentally reverted if care is not taken to revert changes to these files in the PR request.

## Suggested Solution

It would be good to break up this role creation so that ADF deploys a 'bare minimum' role/policy required for ADF to function and a separate file, perhaps global-iam.yml which contains customer specific policies.

My thoughts are that the global.yml continues to create the role, and an example-global-iam.yml file is provided with a policy which attaches itself to the role in the global.yml. This file should never be executed but there should be documentation around renaming it to global-iam.yml which would get executed and wording around IAM best practices and the principal of least privilege.

To be more extensible the logic could say that any yml named `example-*.yml` is skipped and then any yml named `global-*.yml` or `region-*.yml` are deployed based on their current logic.

## What could this look like?

The bootstrap repository would contain additional customized yaml files.
```shell
example-global-iam.yml # Provided by ADF
global.yml # Provided by ADF
global-iam.yml # Custom policies not managed by ADF
deployment/global.yml # Provided by ADF
deployment/global-iam.yml # Custom policies not managed by ADF
deployment/region-custom.yml # Custom policies not managed by ADF
```

### global.yml

Cloudformation role is created as it currently is, however, the policy is reduced to contain only the bare-minimum.

```yaml
  CloudFormationDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "adf-cloudformation-deployment-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Sid: "CloudFormation"
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
          - Effect: Allow
            Sid: "AssumeRole"
            Principal:
              AWS:
                - !Ref DeploymentAccountId # Deployment Account Number
            Action:
              - sts:AssumeRole
      Path: /
  CloudFormationDeploymentPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "adf-cloudformation-deployment-role-policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Sid: "KMS"
            Action:
              - "kms:Decrypt"
              - "kms:DescribeKey"
              - "kms:Encrypt"
              - "kms:GenerateDataKey*"
              - "kms:ReEncrypt*"
            Resource: !Ref KMSArn
      Roles:
        - !Ref CloudFormationDeploymentRole
```

### example-global-iam.yml

A sample policy is provided providing a base set of permissions, perhaps enough to run some of the samples provided by ADF. Once this file is renamed it will not be managed by ADF and will not be overridden during ADF upgrades.

```yaml
  CloudFormationDeploymentCustomPolicy:
    # This is the role that will be used to deploy CloudFormation resources from
    # within the account that it is applied to. You should scope this policy depending
    # On what you would like to deploy within certain Organizational Units.
    # NOTE: below is a sample IAM policy. These policies should be changed to suit your needs.
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "adf-cloudformation-deployment-role-custom-policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Sid: "CloudFormation"
            Action:
              - "ec2:*"
              - "lambda:*"
              - "s3:*"
            Resource:
              - "*"
      Roles:
        - adf-cloudformation-deployment-role
```
