### ISSUE TITLE
Explicitly defined stack_name is ignored

### ISSUE THREAD

**Issue by at7925** [awslabs/aws-deployment-framework#186]
Explicitly defined _stack_name_ in _default_providers_ section is ignored
**Example:** _deployment_maps/defect.yml_
```
---
pipelines:
  - name: wrong-name
    default_providers:
      source:
        provider: codecommit
        properties:
          account_id: 111187061811
      deploy:
        provider: cloudformation
        properties:
          stack_name: adf-correct-name
    targets:
      - path: /deployment
```
Checking StackName in pipeline:
```
aws codepipeline get-pipeline --name adf-pipeline-wrong-name | grep StackName
        "StackName": "adf-wrong-name",
```
**Expected result:**  "StackName": “adf-correct-name”
**Actual result:**  "StackName": "adf-wrong-name”
