### ISSUE TITLE
Approval queries not going to defined slack channel

### ISSUE THREAD

**Issue by eriklz** [awslabs/aws-deployment-framework#195]
When setting up a pipeline which has one Slack channel for pipeline notifications and another Slack channel for an approval target, approval queries goes to the pipeline Slack channel, not the approval channel.

Given the following pipeline config and SecretsManager set up with webhooks for both Slack channels below, notifications for pipeline start and completion goes to **pipeline-channel**. Query for approval also goes to **pipeline-channel**, despite **approval-channel** being configured in the approval target.

```yaml
pipelines:
  - name: the-stuff
    default_providers:
      source:
        provider: codecommit
        properties:
          account_id: "123456789012"
      build:
        provider: codebuild
        properties:
          image: AMAZON_LINUX_2
      deploy:
        provider: codebuild
        properties:
          image: AMAZON_LINUX_2
          spec_filename: deployspec.yml
    params:
      notification_endpoint: pipeline-channel
      restart_execution_on_update: True
    targets:
      - provider: approval
        properties:
          message: New release is ready. Approve?
          notification_endpoint: approval-channel
```
