### ISSUE TITLE
Pipeline with S3 as Deployment Provider fails with Insufficient permissions

### ISSUE THREAD

**Issue by at7925** [awslabs/aws-deployment-framework#202]
Pipeline with S3 as Deployment Provider fails with error:
  Insufficient permissions
  You do not have sufficient permissions to call s3.putObject for the deployment bucket

Example:
```
pipelines:
  - name: poc-s3-deploy
    default_providers:
      source:
        provider: codecommit
        properties:
          account_id: 111111111111
      deploy:
        provider: s3
    targets:
      - target: 999999999999
        properties:
          bucket_name: s3-target-us-east-1-999999999999
          object_key: www
          extract: True
```
**Verifying role:**
```
aws codepipeline get-pipeline --name adf-pipeline-poc-s3-deploy | grep adf-cloudformation-role
    "roleArn": "arn:aws:iam::111111111111:role/adf-cloudformation-role"
```
**Expected**
```
"roleArn": "arn:aws:iam::999999999999:role/adf-cloudformation-role"
```
**Actual Result**
```
"roleArn": "arn:aws:iam::111111111111:role/adf-cloudformation-role"
```
**Conclusion:** incorrect account ID is used for RoleArn
