### ISSUE TITLE
using codebuild as deploy paired with ou path gives unclear error

### ISSUE THREAD

**Issue by bundyfx** [awslabs/aws-deployment-framework#209]
```
   default_providers:
      source:
        provider: codecommit
        properties:
          account_id: "123456789012"
      deploy:
        provider: codebuild
        properties:
          image: AMAZON_LINUX_2
          spec_filename: deployspec.yml`
     targets:
         - /ou/test/123  <-- expecting account id
```

Results in an error about construct names for the stage already existing as it attempts to create multiple codebuild stages with the same name. This works as intended when using account ids as opposed to OU paths as it then only targets a single account and thus there is no duplicate stage name attempts.

The question becomes what would we like this to do when using a path? an idea could be that it fetches the account ids from the ou path and inserts them as an environment variable into a single codebuild project (stage).
