### ISSUE TITLE
Incorrect trust relationship in linked accounts.

### ISSUE THREAD

**Issue by javydekoning** [awslabs/aws-deployment-framework#235]
Some roles in my (newly created) Sub-Accounts are provisioned with role unique ID's in their trust relationsship instead of ARN's. This causes pipelines to fail. 

```
arn:aws:iam::<deployment>:role/adf-codepipeline-role is not authorized to perform AssumeRole on role arn:aws:iam::<target>:role/adf-cloudformation-role
```

![Imgur](https://imgur.com/NZ7NzKH.png)

My global.yml does look correct to me, it also looks correct in the CFN console of the target account. 

```
  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "adf-cloudformation-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${DeploymentAccountId}:role/adf-codepipeline-role
                - !Sub arn:aws:iam::${DeploymentAccountId}:role/adf-cloudformation-role
            Action:
              - sts:AssumeRole
      Path: /
```

But the trust relationship looks like this: 
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "AROAXXXXXXXXXXXXXXXX",
          "AROAXXXXXXXXXXXXXXXX"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

Manually updating these fixes my pipelines. Not sure whether this issue is related to ADF, would love some inputs.
