### ISSUE TITLE
Support for pipelines with build phase only

### ISSUE THREAD

**Issue by thiezn** [awslabs/aws-deployment-framework#27]
Hi,

We have a few lambda functions that we want to share between different accounts. To avoid code duplication we would like to have a single dedicated repository and pipeline for the lambda code. 

We would like to leverage ADF for the creation of the repository and pipeline but are only interested in the build stage of the pipeline. In the buildspec.xml we will package the code and upload to an S3 bucket.

I've tried using the cc-cloudformation type and providing an empty target list to the deployment_map.yml file similar to this:

```yaml
  - name: my-shared-lambda-function
    type: cc-cloudformation
    params:
      - SourceAccountId: 11223344
      - NotificationEndpoint: hello@moorspots.com
      - RestartExecutionOnUpdate: true
    targets: []
```

Unfortunately it fails during the template validation step:

```
cloudformation.validate_template()
 File "/codebuild/output/src223970246/src/adf-build/shared/python/cloudformation.py", line 130, in validate_template
 raise InvalidTemplateError(error.response['Error']['Message'])
errors.InvalidTemplateError: [/Resources/Pipeline/Type/ArtifactStores] 'null' values are not allowed in templates
```

*note* I did see another adf type called cc-s3 but haven't investigated yet if we can use this for our use case. However, I can imagine there are other use cases for this functionality not involving an S3 bucket.

Another solution might be to introduce a pipeline_type that allows you to define your own pipeline deployment stages. Not sure what that would look like but could give flexibility to someone wanting to leverage adf for anything they want to build.

Cheers,
Thiezn

PS. I realize you can leverage Lambda layers for code de-duplication but that only allows you to share modules. It won't allow you to share the full lambda itself for re-use in other templates.
