### ISSUE TITLE
Deployment maps require using OUId as target to resolve OU specific parameters

### ISSUE THREAD

**Issue by hynynen** [awslabs/aws-deployment-framework#294]
I have this deployment map:
```
ipelines:
  - name: vpc-pipeline
    default_providers:
      source:
        provider: codecommit
        properties:
          account_id: 11223344556677
      deploy:
        provider: cloudformation
        properties:
            action: replace_on_failure
            stack_name: ipam-vpc
            template_filename: packaged.yml
    params:  
      restart_execution_on_update: True
    targets:
      - target: ou-tio5-4fqvuabz # OU: /foo/bar
        regions: [eu-west-1, eu-north-1]
```
And the vpc repo has parameter files:
```
params/
├── global.yml
├── ou-123-445678.yml
└── ou-123-567890.yml
```
This works fine. If I change target syntax in deployment map to use human-readable names of OUs (e.g. /foo/bar), generating parameters fails.

It is mentioned in documentation that "When using OU parameter files, the OU must be specified in the deployment map as a target", but this behavior is not clear nor convenient. ADF should be able to deduce OU id from OU name in an organization.
