### ISSUE TITLE
Fetching encrypted parameters from Parameter Store

### ISSUE THREAD

**Issue by hynynen** [awslabs/aws-deployment-framework#298]
I have added RDS database password to Parameter Store and ecrypted it using KMS. I'm using this parameter file in ADF:
```
Parameters:
    DBStorage: '100'
    DBMasterPassword: resolve:/foobar/dbMasterPassword
    DBInstanceType: db.t2.medium
Tags:
    creator: adf
```
When I run the pipeline the CloudFormation stack fails because "password is too long being more than 128 characters long". Only reason I can figure is that ADF gets encrypted secret. Any help with this? Would it be possible to add support for Secrets Manager to parameter resolution? This is supported in deployment maps anyways. Any security concerns when fetching secrets from Parameter Store?
