### ISSUE TITLE
Optional TemplateConfiguration setting enabled by default

### ISSUE THREAD

**Issue by kerimk06** [awslabs/aws-deployment-framework#303]
In the ADF CodePipeline there is an option called ‘TemplateConfiguration’ that is enabled. Normally this option is not enabled by default and is 'optional'. Is it possible to make this optional and is not enabled by default? So we don't have to mess with the CDK. 

<img width="600" alt="Schermafbeelding 2020-10-28 om 10 18 30" src="https://user-images.githubusercontent.com/24234463/97416610-efe20f80-1906-11eb-813d-170387b6a67b.png">

**Comment by sbkok** [comment]
Hi @kerimk06,

The `TemplateConfiguration` is used to pass the parameters and tags to CloudFormation.
Making this optional would imply disabling the parameter and tags logic, so you cannot use the /params folder and ADFs intrinsic functions.

However, if we take a step back, this might be a solution if you are looking to deploy with CDK and cannot do so today:
You can generate empty parameters (or generate params that you use/reference to from your CDK stack using CfnParameter). You can use `cdk synth > template-dev.yml` to synthesize the templates that you need to deploy for a specific account. Your deployment map would be able to reference them like this:

```yaml
  - name: your-pipeline
    default_providers:
      source:
        provider: codecommit
        properties:
          account_id: 111111111111
      build:
        provider: codebuild
      deploy:
        provider: cloudformation
    targets:
      - name: deploy-to-dev
        path: /dev
        properties:
          template_filename: "template-dev.yml"
      - name: deploy-to-test
        path: /test
        properties:
          template_filename: "template-test.yml"
      - approval
      - name: deploy-to-prod
        path: /prod
        properties:
          template_filename: "template-prod.yml"
```

Would that be a solution to the problem you ran into?
If you have a different use case, could you please elaborate what you try to accomplish?
