### ISSUE TITLE
When u

### ISSUE THREAD

**Issue by yvthepief** [awslabs/aws-deployment-framework#305]
When using CDK in combination with ADF, we use codebuild to deploy our CDK templates. We skip the codebuild build fase within a deployment_map in the aws-deployment-framework-pipelines repository. 
But when we use codebuild as the deploy step, the property environment_variables isn't read properly. 
```yaml
pipelines:
  - name: avm
    default_providers:
      source:
        provider: codecommit
        properties:
          account_id: '012345678910' 
      build:
        enabled: False
      deploy:
        provider: codebuild
        properties:
          image: "STANDARD_4_0"
          role: adf-cdk-deployment-role
          environment_variables:
            CDK_ENVIRONMENT: prd
    targets:
      - target: '111111111111'  
        name: "account-1"
      - target: '2222222222'
        name: "account-2"
```
This has to do with the way how adf_codebuild.py reads the environment vars.
```python
def generate_build_env_variables(codebuild, shared_modules_bucket, map_params, target=None):
        _output = {
            "PYTHONPATH": codebuild.BuildEnvironmentVariable(value='./adf-build/python'),
            "ADF_PROJECT_NAME": codebuild.BuildEnvironmentVariable(value=map_params['name']),
            "S3_BUCKET_NAME": codebuild.BuildEnvironmentVariable(value=shared_modules_bucket),
            "ACCOUNT_ID": codebuild.BuildEnvironmentVariable(value=core.Aws.ACCOUNT_ID)
        }
        _build_env_vars = map_params.get('default_providers', {}).get('build', {}).get('properties', {}).get('environment_variables', {})
        for _env_var in _build_env_vars.items():
            _output[_env_var[0]] = codebuild.BuildEnvironmentVariable(value=str(_env_var[1]))
```
