### ISSUE TITLE
Starting pipeline only on completion_trigger

### ISSUE THREAD

**Issue by pszemko-t** [awslabs/aws-deployment-framework#308]
Hi. 
A question or feature request... TBH I have no idea how to set this up currently.
I have a config for two pipelines and the second needs to be started only if the first one finishes 
In the current setup when I upload the file to 
          bucket_name: bucket.name
          object_key: key_2/package.zip
the second pipeline starts. 
But how to configure it in a way that second will run ONLY after it was triggered from first pipeline completion_trigger ?

```
pipelines:
# prerequisites pipeline
  - name: first-pipeline
    regions: eu-west-1
    default_providers: &generic_providers
      source: &generic_source
        provider: s3
        properties:
          account_id: 123412341234
          bucket_name: bucket.name
          object_key: key_1/package.zip
      build:
        provider: codebuild
        properties:
          environment_variables:
            CONTAINS_TRANSFORM: True
      deploy:
        provider: cloudformation
        properties:
          action: REPLACE_ON_FAILURE
          stack_name: adf-something-prereq
    params: 
      restart_execution_on_update: True
    targets: &generic_config_targets
      - path: /deployment
        name: Deploy-to-deployment
    completion_trigger:
      pipelines:
        - config-eu-west-1

  - name: second-pipeline
    regions: eu-west-1
    default_providers: &generic_config_providers
      source:
        provider: s3
        properties:
          account_id: 123412341234
          bucket_name: bucket.name
          object_key: key_2/package.zip
      build:
        provider: codebuild
        properties:
          environment_variables:
            CONTAINS_TRANSFORM: True
      deploy:
        provider: cloudformation
        properties:
          action: REPLACE_ON_FAILURE
          stack_name: adf-something
    params:
      restart_execution_on_update: True
    targets: *generic_config_targets
```
