### ISSUE TITLE
Problem with creating a new pipeline

### ISSUE THREAD

**Issue by memmumm** [awslabs/aws-deployment-framework#314]
We had a functioning aws-deployment-framework-pipeline and created multiple stacks with it successfully. On Friday 8th of January I tried to add another OU (_Production_) to the targets of an existing and functioning pipeline (_cloudwatch-monitoring_) in deployment_maps as follows. 

````
pipelines:
  - name: codedeploy
    default_providers:
      source:
        provider: codecommit
        properties:
          account_id: 111111111111
      deploy:
        provider: cloudformation
        properties:
          action: replace_on_failure
    params:
      restart_execution_on_update: true
    targets:
      - /Production
  - name: cloudwatch-monitoring
    default_providers:
      source:
        provider: codecommit
        properties:
          account_id: 111111111111
      deploy:
        provider: cloudformation
        properties:
          action: replace_on_failure
    params:
      restart_execution_on_update: true
    targets:
      - /Logging
      - /Production
````

Pipeline succeeded but it did not create a stack to the accounts under _Production_ OU. I tried to resolve this by deleting the _cloudwatch-monitoring_  stack and repository, and running the aws-deployment-framework-pipeline again having only _Production_  OU as target. The pipeline succeeded but it did not create the pipeline for _cloudwatch-monitoring_. It only created the stack that creates the repository. In the build details it says: 
`(node:481) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 beforeExit listeners added. Use emitter.setMaxListeners() to increase limit.`

```
`[Container] 2021/01/08 16:18:43 Running command python adf-build/cdk/generate_pipeline_inputs.py
58 | 2021-01-08 16:18:43,455 \| INFO \| __main__ \| ADF Version 3.0.6 \| (generate_pipeline_inputs.py:171)
59 | 2021-01-08 16:18:43,455 \| INFO \| __main__ \| ADF Log Level is INFO \| (generate_pipeline_inputs.py:172)
60 | 2021-01-08 16:18:43,492 \| INFO \| deployment_map \| Loading deployment_map file deployment_maps/security_logging_account.yml \| (deployment_map.py:65)
61 | 2021-01-08 16:18:43,502 \| INFO \| deployment_map \| Loading deployment_map file deployment_maps/iam_roles.yml \| (deployment_map.py:65)
62 | 2021-01-08 16:18:43,506 \| INFO \| deployment_map \| Loading deployment_map file deployment_maps/clusters.yml \| (deployment_map.py:65)
63 | 2021-01-08 16:18:43,522 \| INFO \| deployment_map \| Loading deployment_map file deployment_map.yml \| (deployment_map.py:65)
64 | 2021-01-08 16:18:43,523 \| INFO \| deployment_map \| No default map file found at deployment_map.yml, continuing \| (deployment_map.py:70)
65 |  
66 | [Container] 2021/01/08 16:19:02 Running command cdk synth --app adf-build/cdk/generate_pipeline_stacks.py 1> /dev/null
67 | 2021-01-08 16:19:04,472 \| INFO \| __main__ \| ADF Version 3.0.6 \| (generate_pipeline_stacks.py:25)
68 | 2021-01-08 16:19:04,472 \| INFO \| __main__ \| ADF Log Level is INFO \| (generate_pipeline_stacks.py:26)
69 | 2021-01-08 16:19:04,479 \| INFO \| cdk_stacks.main \| Pipeline creation/update of iam-roles commenced \| (main.py:31)
70 | 2021-01-08 16:19:04,570 \| INFO \| cdk_stacks.main \| Pipeline creation/update of config-aggregator commenced \| (main.py:31)
71 | 2021-01-08 16:19:04,619 \| INFO \| cdk_stacks.main \| Pipeline creation/update of codedeploy commenced \| (main.py:31)
72 | 2021-01-08 16:19:04,660 \| INFO \| cdk_stacks.main \| Pipeline creation/update of cloudwatch-monitoring commenced \| (main.py:31)
73 | 2021-01-08 16:19:04,694 \| INFO \| cdk_stacks.main \| Pipeline creation/update of bastion commenced \| (main.py:31)
74 | 2021-01-08 16:19:04,733 \| INFO \| cdk_stacks.main \| Pipeline creation/update of elasticsearch commenced \| (main.py:31)
75 | 2021-01-08 16:19:04,772 \| INFO \| cdk_stacks.main \| Pipeline creation/update of webapp commenced \| (main.py:31)
76 | 2021-01-08 16:19:04,819 \| INFO \| cdk_stacks.main \| Pipeline creation/update of enable-aws-config commenced \| (main.py:31)
77 | 2021-01-08 16:19:04,853 \| INFO \| cdk_stacks.main \| Pipeline creation/update of rds commenced \| (main.py:31)
78 | 2021-01-08 16:19:04,892 \| INFO \| cdk_stacks.main \| Pipeline creation/update of security-logging-account-templates commenced \| (main.py:31)
79 | (node:486) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 beforeExit listeners added. Use emitter.setMaxListeners() to increase limit
80 | 2021-01-08 16:19:04,932 \| INFO \| cdk_stacks.main \| Pipeline creation/update of vpc commenced \| (main.py:31)
81 |  
82 | [Container] 2021/01/08 16:19:05 Running command python adf-build/cdk/execute_pipeline_stacks.py
83 | 2021-01-08 16:19:05,238 \| INFO \| __main__ \| ADF Version 3.0.6 \| (execute_pipeline_stacks.py:64)
84 | 2021-01-08 16:19:05,238 \| INFO \| __main__ \| ADF Log Level is INFO \| (execute_pipeline_stacks.py:65)
85 |  
86 | [Container] 2021/01/08 16:19:05 Phase complete: BUILD State: SUCCEEDED
87 | [Container] 2021/01/08 16:19:05 Phase context status code:  Message:
88 | [Container] 2021/01/08 16:19:05 Entering phase POST_BUILD
89 | [Container] 2021/01/08 16:19:05 Phase complete: POST_BUILD State: SUCCEEDED
90 | [Container] 2021/01/08 16:19:05 Phase context status code:  Message:`
```
