### ISSUE TITLE
Use 3 different template of Cloud Formation

### ISSUE THREAD

**Issue by 20FS21** [awslabs/aws-deployment-framework#315]
Hello team,
I would like to deploy 3 different cloud formation template to the single account.
In this way in my repository how can I add new template and use it in my deployment_map.yaml pipeline?
Thanks.

**Comment by sbkok** [comment]
Hi @20FS21,

To deploy multiple different CloudFormation templates to a single account, there are three options that could work for this:

#### 1. Separate pipelines and repositories

Ideally, you can work with separate pipelines and repositories. Where each pipeline has its own repository to deploy them into the account. This would be the easiest approach, but obviously only works if the code does not need to live in the same repository. In this case, you define the pipeline separately in your deployment map, like this:

```yaml
  - name: your-first-pipeline
    default_providers:
      source:
        provider: codecommit
        properties:
          account_id: 111111111111
      build:
        provider: codebuild
      deploy:
        provider: cloudformation
    targets:
      - /your/account/ou/or/account/id
      
      
  - name: your-second-pipeline
    default_providers:
      source:
        provider: codecommit
        properties:
          account_id: 111111111111
      build:
        provider: codebuild
      deploy:
        provider: cloudformation
    targets:
      - /your/account/ou/or/account/id
      
  # etc.
```

A major benefit of this approach is that each pipeline has its own lifecycle. Plus any updates to a repository will only affect its related pipeline. Making it simple to reason about.

If the order of the pipeline execution matters, please look into the `completion_trigger` property in the deployment map definition. With this approach, one pipeline trigger another pipeline upon completion.

#### 2. Separate pipelines with a single shared repository

If it would need to live in the same repository and having separate pipelines is an option, you can create a setup as shared in the [mono-repo sample](https://github.com/awslabs/aws-deployment-framework/tree/master/samples/sample-mono-repo). Where all the code would be hosted in the same repository, but deployed using separate pipelines.

However, keep in mind that a single update to the repository will trigger all pipelines. Even when the changes should only affect one template, not all. Additionally, if these templates depend on each other you could still work with the `completion_trigger`, but it will attempt to execute it with every update of the code base, which might cause it to fail first.

#### 3. Single pipeline with a single shared repository

In case the order of the CloudFormation files matters, or when you want to optimize the build phase to be reused and have a single pipeline instead. You can also setup a single deployment map like this:

```yaml
  - name: your-pipeline-name
    default_providers:
      source:
        provider: codecommit
        properties:
          account_id: 111111111111
      build:
        provider: codebuild
      deploy:
        provider: cloudformation
    targets:
      - path: /your/account/ou/or/account/id
        properties:
          template_filename: template-01.yml
      - path: /your/account/ou/or/account/id
        properties:
          template_filename: template-02.yml
      - path: /your/account/ou/or/account/id
        properties:
          template_filename: template-03.yml
```

---

Please let me know if this is helpful or whether you have further questions related to this.

Best regards, Simon
