### ISSUE TITLE
Feature request: Flexible pipeline stages

### ISSUE THREAD

**Issue by engrun** [awslabs/aws-deployment-framework#320]
I know this question has been [raised before](https://github.com/awslabs/aws-deployment-framework/issues/94) but I'll try my luck. 

Occasionally, and increasingly frequent, I find my self wanting a little bit more flexibility when it comes to pipeline stages.
As far as I know, you are limited to 
* one source stage, with one action only
* one build stage, with one action only (although this stage can be disabled)
* one deploy stage with one or more actions (a.k.a. targets)

### It would be a great new feature if the stage definitions could be more flexible. 

**Use cases**

_Source stage:_
Checkout multiple repos,  e.g. one repo with application , and one repo with common tooling.  Only changes to the application-repo would trigger the pipeline

_Build stage:_
This is where I can see most value in providing more than one stage/action, e.g. 
One simple example is to separate the unit-test and integration-test phases. 

Another use-cases would be to have a separate stage for security-scanning the built docker-image before uploading to ecr. 

_Deploy stage:_
Example:  Run some post-deploy bash-scripts using CodeBuild to validate your app

It would be interesting to hear what the rest of the community thinks of this.

**Comment by sbkok** [comment]
Hi @engrun,

We can support a single source only at the moment.
However, for the build and deploy stages, you can define multiple steps and mix-and-match like this:

```yaml
  - name: some-pipeline
    default_providers:
      source:
        provider: codecommit
        properties:
          account_id: 111111111111
      build:
        provider: codebuild
        properties:
          image: STANDARD_5_0
          spec_filename: src/buildspec.yml
      deploy:
        provider: cloudformation
    targets:
      - name: deploy-to-dv
        path: /dev
      - name: perform-integration-tests
        provider: codebuild
        properties:
          spec_filename: src/integrationspec.yml
      - approval
      - name: deploy-to-pr
        path: /prod
```

I hope this helps to fix the limitation you were running into.

Best regards, Simon
