### ISSUE TITLE
Command did not exit successfully pip install --upgrade virtualenv exit status 1

### ISSUE THREAD

**Issue by shamsk88** [awslabs/aws-deployment-framework#361]
```yaml
phases:
  install:
    commands:
      - echo "Installing HashiCorp Packer"
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip && unzip packer.zip
      - echo "Installing jq"
      - curl -qL -o jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x jq
      - echo "Installing boto3"
      - rm -rf venv && mkdir venv
      - pip install --upgrade virtualenv
      - virtualenv venv/
      - . venv/bin/activate
      - pip install -r requirements.txt
```

Anyone help me why we get this issue and solution for it ?

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/51985457/118441666-234f8480-b707-11eb-8859-19e7846c5394.png)

**Comment by shamsk88** [comment]
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
  Could not find a version that satisfies the requirement virtualenv (from versions: )
No matching distribution found for virtualenv
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning

**Comment by sbkok** [comment]
Hi @shamsk88,

I think the problem is the CodeBuild image your pipeline uses is no longer supported.
As the logs show a warning about Python 2.7, that is no longer supported and should not be used.

To work around this problem, I recommend using a recent image in CodeBuild.
You could specify one like this: https://github.com/awslabs/aws-deployment-framework/blame/f9ffc7cb41012a9c8607907eccb96adf255b182d/samples/sample-mono-repo/README.md#L36

Do note that the buildspec for those is updated slightly, as you need to specify what runtimes you need to have like this: https://github.com/awslabs/aws-deployment-framework/blob/f9ffc7cb41012a9c8607907eccb96adf255b182d/samples/sample-mono-repo/apps/alpha/buildspec.yml#L9-L10
You can find more information about the runtimes and how to use them here: https://docs.aws.amazon.com/codebuild/latest/userguide/sample-runtime-versions.html

I hope this helps to resolve the issue.

Best regards, Simon

**Comment by shamsk88** [comment]
Thanks Simon, we are using the below buildspec to build VM to create AMI Image and the we are using pip install -r requirements.txt as below so you mean to say we need to upgrade the version on requirement.txt ?

boto3>=1.2.4
botocore>=1.3.28
jmespath>=0.9.0

BuildSpec YAML:

 variables:
    PACKER_TEMPLATE: "template.json"
    PACKER_VERSION: "1.4.3"

phases:
  install:
    commands:
      - echo "Installing HashiCorp Packer"
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip && unzip packer.zip
      - echo "Installing jq"
      - curl -qL -o jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x jq
      - echo "Installing boto3"
      - rm -rf venv && mkdir venv
      - pip install virtualenv
      - virtualenv venv/
      - . venv/bin/activate
      - pip install -r requirements.txt

**Comment by sbkok** [comment]
Hi @shamsk88,

No, apologies, my answer might not have been clear.
Your requirements.txt is okay, since those use >= they match the latest version as well.

You will need to look into the aws-deployment-framework-bootstrap repository.
That repo contains the deployment map files, inside those files it defines your pipeline that is deployed by ADF.
In the pipeline definition for the pipeline you are working on, you can define what image CodeBuild should use like this: https://github.com/awslabs/aws-deployment-framework/blame/f9ffc7cb41012a9c8607907eccb96adf255b182d/samples/sample-mono-repo/README.md#L33-L36

Add those properties to the repository through a commit + pull request, so they get merged in the main branch and applied to your pipeline.

After this change, your pipeline will fail, as the buildspec.yml file is using the old syntax, not the new one.
In the repository used by the pipeline (that contains the buildspec.yml and requirements.txt, etc), you need to edit the buildspec.yml file and change it to:

```yaml
version: 0.2

variables:
  PACKER_TEMPLATE: "template.json"
  PACKER_VERSION: "1.4.3"

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing HashiCorp Packer"
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip && unzip packer.zip
      - echo "Installing jq"
      - curl -qL -o jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x jq
      - echo "Installing boto3"
      - rm -rf venv && mkdir venv
      - pip install virtualenv
      - virtualenv venv/
      - . venv/bin/activate
      - pip install -r requirements.txt
```

I hope this fixes your issue.

Best regards, Simon
