### ISSUE TITLE
Disabling the deploy stage does not work

### ISSUE THREAD

**Issue by sbkok** [awslabs/aws-deployment-framework#365]
When you disable the deploy stage like this:

```yaml
- name: sample-codebuild-only
    default_providers:
      source:
        provider: codecommit
        properties:
          account_id: 111111111111
      build:
        provider: codebuild
      deploy:
        provider: cloudformation
        enabled: False
```

It fails with the error: `Wrong key 'enabled' in {'provider': 'cloudformation', 'enabled': False}`.
Even though it is supposed to work according to the default deploy provider schema. See: https://github.com/awslabs/aws-deployment-framework/blob/c54cbf30eeff21de944a204c26f00e1447d2449e/src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/schema_validation.py#L277-L284

The problem is that the individual providers that it matches against does not support the enabled property. See: 
https://github.com/awslabs/aws-deployment-framework/blob/c54cbf30eeff21de944a204c26f00e1447d2449e/src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/schema_validation.py#L286

and:

https://github.com/awslabs/aws-deployment-framework/blob/c54cbf30eeff21de944a204c26f00e1447d2449e/src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/schema_validation.py#L166-L169
