### ISSUE TITLE
Feature request: Support for CODEBUILD_CLONE_REF in Source of deployment map

### ISSUE THREAD

**Issue by nagmesh** [awslabs/aws-deployment-framework#387]
I would like to have `CODEBUILD_CLONE_REF` as an option on [source output artifact format](https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CodeCommit.html#action-reference-CodeCommit-config) so that I can do some git specific actions in Codebuild

**Comment by StewartW** [comment]
Do you see this just as a property on the code commit source provider? 
```
default_providers:
  source:
    provider: codecommit
    properties:
      output_artifact_format:  CODEBUILD_CLONE_REF | CODE_ZIP
```
Would that work you?
