### ISSUE TITLE
Deploy applications from the Serverless Application Repository

### ISSUE THREAD

**Issue by Nr18** [awslabs/aws-deployment-framework#411]
## Introduction

Having the ability to easily deploy an application from the Serverless Application Repository could make our lives a lot easier. Imagine that you need to deploy a template across x amount of accounts/regions but it's likely never going to change or you don't manage it completely. 

In these cases if that template is hosted on the Serverless Application Repository you could utilise that in ADF.

## Goal

Support deployment of applications hosted in the Serverless Application Repository.

## Proposal (Work in progress)

A pipeline definition could look like this for the deployment of a SAR application.

```yaml
  - name: my-sar-application
    default_providers:
      source:
        provider: sar
        properties:
          application_id: 'arn:aws:serverlessrepo:us-east-1:012345678901:applications/my-application'
          version: 1.0.0
          parameters:
            StringParameter: parameter-value
            IntegerParameter: 2
      build: # Optional, if given it allows you to overwrite the BuildSpec and additional tweaks/scanning/compliancy checks
        provider: code-build
        properties:
          image: STANDARD_4_0
      deploy:
        provider: cloudformation
    targets:
      - name: Deploy
        path: /path/to/accounts
        regions: eu-west-1
```

So, the general idea that I had was to just generate a CloudFormation template like this (or use CloudFormation parameters):

```yaml
Resources:
  Type: AWS::Serverless::Application
  Properties:
    Location:
      ApplicationId: 'arn:aws:serverlessrepo:us-east-1:012345678901:applications/my-application'
      SemanticVersion: 1.0.0
    Parameters:
      StringParameter: parameter-value
      IntegerParameter: 2
```

Any 👍 or feedback, comments, remarks, concerns are appreciated!
