### ISSUE TITLE
Breaking aws-deployment-framework-pipelines

### ISSUE THREAD

**Issue by Nr18** [awslabs/aws-deployment-framework#425]
Due to the following issue: 
- aws/aws-cdk#18324
- aws/aws-cdk#18328

Your `aws-deployment-framework-pipelines` pipeline might be impacted. The reason for this is because the CDK version is pinned  to a specific version. 

For example the buildspec from 3.0.6 is

```yaml
version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
      nodejs: 10
  pre_build:
    commands:
      - npm install cdk@1.32 -g -y --quiet --no-progress
      - aws s3 cp s3://$SHARED_MODULES_BUCKET/adf-build/ ./adf-build/ --recursive --quiet
      - pip install -r adf-build/requirements.txt -q -t ./adf-build
  build:
    commands:
      - cdk --version
      - chmod 755 adf-build/cdk/execute_pipeline_stacks.py adf-build/cdk/generate_pipeline_inputs.py adf-build/cdk/generate_pipeline_stacks.py
      - python adf-build/cdk/generate_pipeline_inputs.py
      - cdk synth --app adf-build/cdk/generate_pipeline_stacks.py 1> /dev/null
      - python adf-build/cdk/execute_pipeline_stacks.py
```

The current version uses:

```yaml
version: 0.2
  phases:
    install:
      runtime-versions:
        python: 3.9
        nodejs: 12
    pre_build:
      commands:
        - npm install cdk@1.137 -g -y --quiet --no-progress
        - aws s3 cp s3://$SHARED_MODULES_BUCKET/adf-build/ ./adf-build/ --recursive --quiet
        - pip install -r adf-build/requirements.txt -q -t ./adf-build
    build:
      commands:
        - cdk --version
        - chmod 755 adf-build/cdk/execute_pipeline_stacks.py adf-build/cdk/generate_pipeline_inputs.py adf-build/cdk/generate_pipeline_stacks.py adf-build/cdk/clean_pipelines.py
        - python adf-build/cdk/generate_pipeline_inputs.py
        - cdk synth --no-version-reporting --app adf-build/cdk/generate_pipeline_stacks.py 1> /dev/null
        - python adf-build/cdk/execute_pipeline_stacks.py
    post_build:
      commands:
        - python adf-build/cdk/clean_pipelines.py
```

## Workaround

By changing the version from `1.32` or `1.137` to `2.5.0` manually would "fix" the pipeline again.

## (Proposed) Solution

Bump the version to 2.5.0 in the buildspec
