### ISSUE TITLE
Idea: allow use of all CloudFormation update types (e.g. also "Create or update a stack")

### ISSUE THREAD

**Issue by ottokruse** [awslabs/aws-deployment-framework#44]
Possible types:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/continuous-delivery-codepipeline-action-reference.html

**Comment by bundyfx** [comment]
love it - done, will be in 0.3.1

eg:

```
pipelines:  
  - name: sample-vpc
    type: cc-cloudformation
    action: create_update # optional but could also be replace_on_failure etc *(defaults to change set create/execute)*
```
