### ISSUE TITLE
feat: CI/CD improvements - Consider implementing yamllint

### ISSUE THREAD

**Issue by javydekoning** [awslabs/aws-deployment-framework#463]
Some examples have inconsistent indentation. For example:

https://github.com/awslabs/aws-deployment-framework/blob/master/samples/sample-ecs-cluster/template.yml#L8-L13

Others like the below have incorrect syntax:

https://github.com/awslabs/aws-deployment-framework/blob/cdfa538e2aaf8d2b55260678f4e57cdc954c5d96/src/lambda_codebase/initial_commit/bootstrap_repository/example-adfconfig.yml#L18-L20

`auto-create-repositories` should be a property of `scm:` hence needs to be indented. 

To start I'm proposing to implement yamllint with the following `.yamllint` config file:

```
---
yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

rules:
  braces: enable
  brackets: enable
  colons: enable
  commas: enable
  comments:
    level: warning
  comments-indentation:
    level: warning
  document-end: disable
  document-start: disable
  empty-lines: enable
  empty-values: disable
  hyphens: enable
  indentation: enable
  key-duplicates: enable
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file: disable
  new-lines: enable
  octal-values: disable
  quoted-strings: disable
  trailing-spaces: enable
  truthy:
    level: warning
```

This should catch the above syntax error and improve overall code consistency.
