### ISSUE TITLE
[ADF bootstrap] using IAM trust relations with internal AWS role IDs lead to issues

### ISSUE THREAD

**Issue by AndreasAugustin** [awslabs/aws-deployment-framework#472]
Hi dear ADF team,

Due to broken ADF pipeline creations we needed to recreate our `adf-global-base-deployment` stack within our deployment account.
This led to a recreation of the underlying `adf-codepipeline-role` Role.
For the deployments (e.q. Cloudformation) the trust relations to the `adf-cloudformation-role` is set to

```yaml
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${DeploymentAccountId}:role/adf-codepipeline-role
                - !Sub arn:aws:iam::${DeploymentAccountId}:role/adf-cloudformation-role
            Action:
              - sts:AssumeRole
```

which will be `AWS` internal replaced with the internal AWS role ID.
Due to this fact we run into several issues.

[@AndyEffa](https://github.com/AndyEfaa) had the idea to switch to a condition based account principal  so that such errors do not occur anymore.

Example:

```yaml
- Effect: Allow
            Action: 
              - 'sts:AssumeRole'
            Condition:
              StringEquals:
               'aws:PrincipalArn': 
                  - !Sub 'arn:aws:iam::${DeploymentAccountId}:role/adf-codepipeline-role'
                  - !Sub 'arn:aws:iam::${DeploymentAccountId}:role/adf-cloudformation-role'
            Principal:
              AWS: !Join
                - ''
                - - 'arn:'
                  - !Ref 'AWS::Partition'
                  - !Sub ':iam::${DeploymentAccountId}:root'
```

We want to throw in this idea to help other people avoid this issue.
