### ISSUE TITLE
Idea: Adding optional schedule to ADF pipelines

### ISSUE THREAD

**Issue by thiezn** [awslabs/aws-deployment-framework#48]
Hi,

It would be helpful to be able to add a [schedule](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html) to [trigger a pipeline](https://docs.aws.amazon.com/codepipeline/latest/userguide/pipelines-trigger-source-schedule-console.html) on a certain time. Would it be possible to integrate this into ADF so we can do something like the following in the deployment_map.yml:

```yaml
  # Creates, prepares and moves accounts in the AWS organization
  - name: accounts
    type: cc-buildonly
    params:
      - Schedule: cron(0 12 * * ? *)
      - SourceAccountId: 1122334455
      - NotificationEndpoint: hello@moorspots.com
      - RestartExecutionOnUpdate: true
```

The Schedule parameter would take a [Cloudwatch ScheduledEvent](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html)

Cheers,
Thiezn
