### ISSUE TITLE
[Bug?] Maybe a small bug in buildspec in cloudformation template

### ISSUE THREAD

**Issue by AndreasAugustin** [awslabs/aws-deployment-framework#527]
Reading the code I have faced a possible bug in 
[src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml][ref]

master branch

Line 624 - 642

```yaml
Source:
        Type: NO_SOURCE
        BuildSpec: !Sub |
          version: 0.2
          phases:
            install:
              runtime-versions:
                python: 3.9
                nodejs: 14
              commands:
                - npm install cdk@1.169 -g -y --quiet --no-progress
                - aws s3 cp s3://$SHARED_MODULES_BUCKET/adf-build/ ./adf-build/ --recursive --quiet
                - pip install -r adf-build/requirements.txt -q -t ./adf-build
                - chmod 755 adf-build/cdk/execute_pipeline_stacks.py  adf-build/cdk/generate_pipeline_stacks.py
            build:
              commands:
                - cdk --version
                - mkdir cdk_inputs
                - cp definition.json cdk_inputs/definition.json
                - cdk synth --app adf-build/cdk/generate_pipeline_stacks.py -vv
                - python adf-build/cdk/execute_pipeline_stacks.py
      ServiceRole: !GetAtt PipelineManagementCodeBuildProjectRole.Arn
```

There in special the `adf-build/cdk/` parts. But the mentioned python scripts are located in `adf-build/shared/cdk/`
Not sure if some magic is moving the parts, but I guess no.

[ref]: https://github.com/awslabs/aws-deployment-framework/blob/master/src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml
