### ISSUE TITLE
[Bug]: Long and similar pipelines names in same deployment map prevents pipeline from being created

### ISSUE THREAD

**Issue by avolip** [awslabs/aws-deployment-framework#640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When pipelines with similar names that differ after the 30th character are defined in the same deployment map the ADFPipelineManagementStateMachine state machine is not triggered correctly.

Consider the following deployment map `mydeploymentmap.yml`

```yaml
pipelines:
  - name: kpi-dataplatform-qwerty-logistic
    default_providers:
      source:
        provider: codecommit
        properties:
          account_id: [...]
      build:
        provider: codebuild
        properties:
          image: "STANDARD_5_0"
          environment_variables:
            CONTAINS_TRANSFORM: False

  - name: kpi-dataplatform-qwerty-logistic-dev
    default_providers:
      source:
        provider: codecommit
        properties:
          repository: kpi-dataplatform-kupit-logistic
          branch: dev
          account_id: [...]
      build:
        provider: codebuild
        properties:
          image: "STANDARD_5_0"
          environment_variables:
            CONTAINS_TRANSFORM: False
```

### Expected Behavior

ADFPipelineManagementStateMachine gets executed twice and two CodePipeline pipelines get created.

### Current Behavior

ADFPipelineManagementStateMachine gets executed only once and only the first pipeline gets created

### Steps To Reproduce

Deploy the provided example deployment map

### ADF Version

3.2.0
