### ISSUE TITLE
Pipeline completion triggers

### ISSUE THREAD

**Issue by samaneh-utter** [awslabs/aws-deployment-framework#82]
Pipeline#1 should be able to trigger Pipeline#2 or any other resource that is mentioned in the target after execution succeed. This can be done by CloudWatchEvents triggering on completion of the source pipeline to start execution of the target pipeline.

```
pipelines:
  - name: sample-vpc  # The name of your pipeline (This will match the name of your repository)
    type: cc-cloudformation  # The pipeline_type you wish to use for this pipeline
    completion-trigger:
      pipeline:
        - sample-iam
    params:
      - SourceAccountId: 558421765047  # The source account that will hold the codebase
    targets:  # Deployment stages
      - /banking/testing
      - approval
      - /banking/production
```

**Comment by bundyfx** [comment]
Great idea, lets add this into a release after Release 1.1.0

**Comment by at7925** [comment]
Agree, triggering one pipeline by another pipeline is a great idea but it would be even better if we have a trigger(or triggers) in the second-pipeline to start it when event happens in first pipeline

```
pipelines:
  - name: sample-vpc  # The name of your pipeline (This will match the name of your repository)
    type: cc-cloudformation  # The pipeline_type you wish to use for this pipeline
    params:
      - SourceAccountId: 999921765047  # The source account that will hold the codebase
    targets:  # Deployment stages
      - /banking/testing
      - approval
      - /banking/production

- name: second-pipeline 
  type: cc-buildonly
  triggers:    # by default is triggered by change in CC repository, unless explicitly specified otherwise 
     - pipeline: sample-vpc
       target: /banking/testing
     - pipeline: sample-vpc
        target: /banking/production
   params:
      - SourceAccountId: 999921765047  # The source account that will hold the codebase
```
In this example the second-pipeline will be triggered twice after successful deployment by sample-vpc to specified targets. 
Such pipeline interconnection would be particular great for starting testing processes or even an approval process
