### ISSUE TITLE
Create CodeCommit repo from deployment_map entry

### ISSUE THREAD

**Issue by triha74** [awslabs/aws-deployment-framework#88]
I would really like to simplify creation of a new repo to make it "one click to get repo and pipe".

By adding a "create-repo: true" attribute ADF should be able to create a code commit repo by launching a CF in the SourceAccount. The CF could be a template provided by the pipeline generator repo so that users can extend it.
```
pipelines:
  - name: my-sample-app
    create-repo: true
    type: cc-customdeploy
    params:
      - SourceAccountId: 9876543210
    targets:
      - path: 12345667899
```

**Comment by bundyfx** [comment]
Agreed I think the repo should be automatically created if using CodeCommit as a source, we have the account Id and we know the repo name so this makes sense. I think this would be best as the default if using CodeCommit, I cannot see a scenario when you would not want the repo created. Should we bother with the 'create-repo' key?

**Comment by triha74** [comment]
It might be that users want to create the repo them selfs using CF and including event lambdas and stuff.

**Comment by bundyfx** [comment]
Ok, I like the idea. Maybe we should make it the default then, and it can be opt out of with:

```
create-repo: false
```

**Comment by thiezn** [comment]
+1

We currently use a seperate ADF managed pipeline that just churns out CodeCommit repositories including some IAM Roles that prevents pushing directly to master. Recently AWS CodeCommit allows you to provide initial content (e.g. README.md and .gitignore templates) by pointing to a zip file on an s3 bucket.

Would be great if this can be made possible through ADF as well. We could add another parameter pointing to the zip file:

````
pipelines:
  - name: my-sample-app
    create-repo: true
    initial-repo-content: arn::s3:mybucket/initialrepocontent.zip
```

**Comment by thiezn** [comment]
Something else, shouldn't the create-repo parameter fit better in the params section like so:

```yaml
pipelines:
  - name: my-sample-app
    type: cc-cloudformation
    params:
     - create-repo: true
     - initial-repo-content: arn::s3:mybucket/initialrepocontent.zip
```
