### ISSUE TITLE
Custom tags on Pipe CF stacks

### ISSUE THREAD

**Issue by triha74** [awslabs/aws-deployment-framework#91]
I would like to create tags on my repos for pipes and apps created by ADF. I’d like to use it to control access, split cost ect.

I’m thinking something like this should work.

```
pipelines:
  - name: blue-example
    type: cc-cloudformation
    tags:
        - Service: Blue
        - Owner: Me
    params:
      - SourceAccountId: 0987654321
    targets:
      - /qa
      - /prod
```
