### ISSUE TITLE
Global vs regional

### ISSUE THREAD

**Issue by larsrnielsen** [awslabs/aws-deployment-framework#96]
After I cloned the the bootstrap repository I added a folder “sharedservice” with a “non-prod” subfolder. Here I added a global.yml and regional.yml file. The global has IAM resources and the regional has a few resources like S3 access log bucket. In the future I will add stuff like cloudtrail enablement and so on. 

I am able to bootstrap an account with global.yml but regional.yml is never included in the bootstrap process. Is there some reason for this?

Lars

**Comment by bundyfx** [comment]
Hi @larsrnielsen 

regional.yml will bootstrap accounts in regions _**other than**_ the global region. When setting up ADF you would of defined a global (main) region, this region will be the target for any global.yml files found. You can also define target regions, these regions will be the target for any regional.yml files. Currently ADF does not apply the regional.yml to the global region even if its included as a target region. 

I would recommend creating a deployment pipeline in the deployment account to deploy resources (such as CloudTrail, Logging resources) in a scalable and streamlined manner as oppose to bootstrapping these into the accounts.

**Comment by larsrnielsen** [comment]
Hi,

   Thanks for your explanation, it makes sense. Regarding bootstrap vs
pipeline, I am planning to create a service catalog based account vending
machine that would create new accounts under a certain OU, like
applications or sandboxes. By moving the necessary network (connection to
Transit Gateway), compliance (CloudTrail, Cloud Custodian, ...)  and
security configuration (VPC flow logs, GuardDuty client, ...) to bootstrap
instead of pipeline, I would avoid manual reconfiguration of the deployment
map. The pipeline part is then for the infrastructure supporting the
application. Or should I go in another direction?

Lars

fre. 12. jul. 2019 kl. 21.46 skrev Flynn Bundy <notifications@github.com>:

**Comment by bundyfx** [comment]
Hi @larsrnielsen 

There is no need to reconfigure the deployment map for each new account, just set it up to target the OU's you would like to have your foundation stacks deployed to, then set it to ExecuteOnPipelineUpdate. For example:

```
pipelines:
  - name: sample-pipeline  # The name of your pipeline (This will match the name of your repository)
    type: cc-cloudformation  # The pipeline_type you wish to use for this pipeline
    params:
      - SourceAccountId: 111111111111  # The source account that will hold the codebase
      - RestartExecutionOnUpdate: true # This means it will automatically trigger when a new account moves into any of the below OU's (After they have been bootstrapped)
    targets:  # Deployment stages
      - /business_unit/testing
      - /business_unit/production
```

You can create multiple pipelines for different foundation aspects, you can even set up pipelines to have completion triggers that will trigger other pipelines when they complete successfully. This is the preferred way to go when deploying resources. The base stacks are mostly just for setting up ADF roles that are then assumed by pipelines. Where possible its best to avoid adding more resources to them.
