### ISSUE TITLE
Adding CAPABILITY_AUTO_EXPAND to CloudFormation Execute Stack

### ISSUE THREAD

**Issue by thiezn** [awslabs/aws-deployment-framework#98]
Hi,

I'm trying to create a Generic Secret Manager Rotator lambda function based on an application published in SAR and am using the cc-cloudformation pipeline. Here's an excerpt of our CloudFormation template:

```yaml
  SecretsManagerRotationTemplate:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:297356227824:applications/SecretsManagerRotationTemplate
        SemanticVersion: 1.0.112
      Parameters: 
        # The Secrets Manager endpoint to hit
        endpoint: !Sub https://secretsmanager.${AWS::Region}.amazonaws.com
        # The name of the lambda function
        functionName: !Ref MyLambdaFunction
```

The pipeline currently fails in the Deploy stage CHANGE_SET_REPLACE action as it's missing the CAPABILITY_AUTO_EXPAND capability.

Would it be possible to add ,CAPABILITY_AUTO_EXPAND in the following two templates?

[cc-cloudformation](https://github.com/awslabs/aws-deployment-framework/blob/a0ed5d5cb1c9d0e51004ecf01d84d2e23da65f6e/src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/cc-cloudformation.yml.j2#L321) [cc-github](https://github.com/awslabs/aws-deployment-framework/blob/a0ed5d5cb1c9d0e51004ecf01d84d2e23da65f6e/src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/github-cloudformation.yml.j2#L347)

Cheers,
Mathijs
